/**
 * generated by Xtext 2.12.0-SNAPSHOT
 */
package pf.ide;

import pf.ide.AbstractPfIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class PfIdeModule extends AbstractPfIdeModule {
}
