/*
 * generated by Xtext 2.13.0
 */
package pf.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import pf.parser.antlr.internal.InternalPfParser;
import pf.services.PfGrammarAccess;

public class PfParser extends AbstractAntlrParser {

	@Inject
	private PfGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalPfParser createParser(XtextTokenStream stream) {
		return new InternalPfParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "ProblemDiagram";
	}

	public PfGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PfGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
