/*
 * generated by Xtext 2.13.0
 */
package pf.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import pf.services.PfGrammarAccess;

@SuppressWarnings("all")
public class PfSyntacticSequencer extends AbstractSyntacticSequencer {

	protected PfGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Link_ColonKeyword_4_0_q;
	protected AbstractElementAlias match_Node_ColonKeyword_2_0_q;
	protected AbstractElementAlias match_Node___LeftCurlyBracketKeyword_3_0_RightCurlyBracketKeyword_3_3__q;
	protected AbstractElementAlias match_Phenomenon_ColonKeyword_3_0_q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (PfGrammarAccess) access;
		match_Link_ColonKeyword_4_0_q = new TokenAlias(false, true, grammarAccess.getLinkAccess().getColonKeyword_4_0());
		match_Node_ColonKeyword_2_0_q = new TokenAlias(false, true, grammarAccess.getNodeAccess().getColonKeyword_2_0());
		match_Node___LeftCurlyBracketKeyword_3_0_RightCurlyBracketKeyword_3_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getNodeAccess().getLeftCurlyBracketKeyword_3_0()), new TokenAlias(false, false, grammarAccess.getNodeAccess().getRightCurlyBracketKeyword_3_3()));
		match_Phenomenon_ColonKeyword_3_0_q = new TokenAlias(false, true, grammarAccess.getPhenomenonAccess().getColonKeyword_3_0());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Link_ColonKeyword_4_0_q.equals(syntax))
				emit_Link_ColonKeyword_4_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Node_ColonKeyword_2_0_q.equals(syntax))
				emit_Node_ColonKeyword_2_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Node___LeftCurlyBracketKeyword_3_0_RightCurlyBracketKeyword_3_3__q.equals(syntax))
				emit_Node___LeftCurlyBracketKeyword_3_0_RightCurlyBracketKeyword_3_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Phenomenon_ColonKeyword_3_0_q.equals(syntax))
				emit_Phenomenon_ColonKeyword_3_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     ':'?
	 *
	 * This ambiguous syntax occurs at:
	 *     phenomena+=Phenomenon '}' (ambiguity) description=STRING
	 *     to=[Node|ID] (ambiguity) description=STRING
	 */
	protected void emit_Link_ColonKeyword_4_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ':'?
	 *
	 * This ambiguous syntax occurs at:
	 *     type=NodeType (ambiguity) description=STRING
	 */
	protected void emit_Node_ColonKeyword_2_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     description=STRING (ambiguity) (rule end)
	 *     type=NodeType (ambiguity) (rule end)
	 */
	protected void emit_Node___LeftCurlyBracketKeyword_3_0_RightCurlyBracketKeyword_3_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ':'?
	 *
	 * This ambiguous syntax occurs at:
	 *     name=ID (ambiguity) description=STRING
	 */
	protected void emit_Phenomenon_ColonKeyword_3_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
