/**
 * generated by Xtext 2.13.0
 */
package pf.scoping;

import pf.scoping.AbstractPfScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class PfScopeProvider extends AbstractPfScopeProvider {
}
