/**
 * generated by Xtext 2.13.0
 */
package pf.pf;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Link</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link pf.pf.Link#getFrom <em>From</em>}</li>
 *   <li>{@link pf.pf.Link#getType <em>Type</em>}</li>
 *   <li>{@link pf.pf.Link#getTo <em>To</em>}</li>
 *   <li>{@link pf.pf.Link#getPhenomena <em>Phenomena</em>}</li>
 *   <li>{@link pf.pf.Link#getDescription <em>Description</em>}</li>
 * </ul>
 *
 * @see pf.pf.PfPackage#getLink()
 * @model
 * @generated
 */
public interface Link extends EObject
{
  /**
   * Returns the value of the '<em><b>From</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>From</em>' reference.
   * @see #setFrom(Node)
   * @see pf.pf.PfPackage#getLink_From()
   * @model
   * @generated
   */
  Node getFrom();

  /**
   * Sets the value of the '{@link pf.pf.Link#getFrom <em>From</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>From</em>' reference.
   * @see #getFrom()
   * @generated
   */
  void setFrom(Node value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link pf.pf.LinkType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see pf.pf.LinkType
   * @see #setType(LinkType)
   * @see pf.pf.PfPackage#getLink_Type()
   * @model
   * @generated
   */
  LinkType getType();

  /**
   * Sets the value of the '{@link pf.pf.Link#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see pf.pf.LinkType
   * @see #getType()
   * @generated
   */
  void setType(LinkType value);

  /**
   * Returns the value of the '<em><b>To</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>To</em>' reference.
   * @see #setTo(Node)
   * @see pf.pf.PfPackage#getLink_To()
   * @model
   * @generated
   */
  Node getTo();

  /**
   * Sets the value of the '{@link pf.pf.Link#getTo <em>To</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>To</em>' reference.
   * @see #getTo()
   * @generated
   */
  void setTo(Node value);

  /**
   * Returns the value of the '<em><b>Phenomena</b></em>' containment reference list.
   * The list contents are of type {@link pf.pf.Phenomenon}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Phenomena</em>' containment reference list.
   * @see pf.pf.PfPackage#getLink_Phenomena()
   * @model containment="true"
   * @generated
   */
  EList<Phenomenon> getPhenomena();

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see pf.pf.PfPackage#getLink_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link pf.pf.Link#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

} // Link
