/**
 * generated by Xtext 2.13.0
 */
package pf.pf;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Node</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link pf.pf.Node#getName <em>Name</em>}</li>
 *   <li>{@link pf.pf.Node#getType <em>Type</em>}</li>
 *   <li>{@link pf.pf.Node#getDescription <em>Description</em>}</li>
 *   <li>{@link pf.pf.Node#getHiddenPhenomena <em>Hidden Phenomena</em>}</li>
 *   <li>{@link pf.pf.Node#getSubproblem <em>Subproblem</em>}</li>
 *   <li>{@link pf.pf.Node#getProblemNodeRef <em>Problem Node Ref</em>}</li>
 *   <li>{@link pf.pf.Node#getProblemRef <em>Problem Ref</em>}</li>
 *   <li>{@link pf.pf.Node#getHref <em>Href</em>}</li>
 * </ul>
 *
 * @see pf.pf.PfPackage#getNode()
 * @model
 * @generated
 */
public interface Node extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see pf.pf.PfPackage#getNode_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link pf.pf.Node#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link pf.pf.NodeType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see pf.pf.NodeType
   * @see #setType(NodeType)
   * @see pf.pf.PfPackage#getNode_Type()
   * @model
   * @generated
   */
  NodeType getType();

  /**
   * Sets the value of the '{@link pf.pf.Node#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see pf.pf.NodeType
   * @see #getType()
   * @generated
   */
  void setType(NodeType value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see pf.pf.PfPackage#getNode_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link pf.pf.Node#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Hidden Phenomena</b></em>' containment reference list.
   * The list contents are of type {@link pf.pf.Phenomenon}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Hidden Phenomena</em>' containment reference list.
   * @see pf.pf.PfPackage#getNode_HiddenPhenomena()
   * @model containment="true"
   * @generated
   */
  EList<Phenomenon> getHiddenPhenomena();

  /**
   * Returns the value of the '<em><b>Subproblem</b></em>' containment reference list.
   * The list contents are of type {@link pf.pf.ProblemDiagram}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Subproblem</em>' containment reference list.
   * @see pf.pf.PfPackage#getNode_Subproblem()
   * @model containment="true"
   * @generated
   */
  EList<ProblemDiagram> getSubproblem();

  /**
   * Returns the value of the '<em><b>Problem Node Ref</b></em>' reference list.
   * The list contents are of type {@link pf.pf.Node}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Problem Node Ref</em>' reference list.
   * @see pf.pf.PfPackage#getNode_ProblemNodeRef()
   * @model
   * @generated
   */
  EList<Node> getProblemNodeRef();

  /**
   * Returns the value of the '<em><b>Problem Ref</b></em>' reference list.
   * The list contents are of type {@link pf.pf.ProblemDiagram}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Problem Ref</em>' reference list.
   * @see pf.pf.PfPackage#getNode_ProblemRef()
   * @model
   * @generated
   */
  EList<ProblemDiagram> getProblemRef();

  /**
   * Returns the value of the '<em><b>Href</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Href</em>' attribute list.
   * @see pf.pf.PfPackage#getNode_Href()
   * @model unique="false"
   * @generated
   */
  EList<String> getHref();

} // Node
